### ISSUE TITLE
Fuse does not have a remout option

### ISSUE THREAD

**Issue by quobjoern** [quobyte/quobyte-deploy#16]
The client-ds.yaml crashes when the quobyte mount point exists since FUSE doesn't have this option. It should probably fusermount -uz

**Comment by johscheuer** [comment]
Could you tell which version of Quobyte you are using?

**Comment by quobjoern** [comment]
I'm using 1.4 (not announced yet, but available from the repo), but I think FUSE itself never supported the remount option.
