### ISSUE TITLE
Registries in replication controller feasible?

### ISSUE THREAD

**Issue by sttts** [quobyte/quobyte-deploy#3]
Would it be feasible to have the registry instances in a normal registration controller with an "empty dir" volume mount?

Having labels on 3 designated nodes is not really elastic cloud friendly i.e. where nodes come and go during rolling cluster updates.

If discovery is an issue, the trick to have 3 services with 3 virtual fixed IPs might help (like one deploys etcd on Kubernetes).

**Comment by quofelix** [comment]
Discovery is solved by SRV.

The issue is stickyness: if I reboot the cluster, will at least two registries end up starting with access to their state?

**Comment by cornelius-keller** [comment]
What about using a daemonset for the registry and mount a specific host dir so that the registry node will find its state after a reboot?

**Comment by sttts** [comment]
Yes, a daemon set with node labels could be used.
